name: notification
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^0.14.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  http: ^0.13.3
  latlong2: ^0.8.1
  google_maps_flutter: ^2.9.0
  delightful_toast: ^1.0.0 # Add this line for delightful_toast package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/nextcar.png
    - assets/car.png
    - assets/headphones.png
    - assets/home.png
    - assets/newspaper.png
    - assets/dashboard.png